### ISSUE TITLE
No module named honssh.config

### ISSUE THREAD

**Issue by stuartt44** [tnich/honssh#113]
Hi,

Im a complete Linux noob and as part of a uni project need to setup HonSSH, I believe I've installed everything correctly and when starting to start honssh I keep getting the subject error.

![image](https://user-images.githubusercontent.com/35697713/37091822-792d3c7e-2201-11e8-93d5-2bd17d9ec876.png)

Been following this guide (but on host rather than virtual env):
https://www.linkedin.com/pulse/analyse-your-attackers-vectors-ssh-honey-pot-robert-putt

There is a honssh.cfg file so not really sure what to do. Is this the file its referring to or is there another file in a different location?

**Comment by stuartt44** [comment]
Thanks for answering, I've done that - **pythonpath="/root/honssh"** and still get the same error. Any other ideas?

I've looked at those pages and they're not really helpful for newbies like myself that have very limited Linux knowledge, I can essentially install stuff and navigate the files, but would have no idea how to install and actually start HonSSH.

**Comment by robputt796** [comment]
Hi @stuartt44 

Is your host listening publicly on the internet? I'd be more than happy to SSH in and take a poke at this for you as I am guessing time is of the essence due to it being a university project.

Best Regards,

Rob

**Comment by 0Nightsedge0** [comment]
Hi @stuartt44 

And I have the same problem about the **PYTHONPATH**.
`export PYTHONPATH="$PYTHONPATH:/folder/to/honssh"` and `export PYTHONPATH=/path/to/honssh` are not work for me, too. (idk why...)

Anyway, python scripts are easy to debug.

## Try to fix it
In **honssh.tac**, add `sys.path.append('/path/to/honssh')` before load honssh.config module.

And then, **No module named GeoIP** occurred in **output_handler.py**.
Since I installed **python-geoip** by using pip, the module name should be **geoip**.
So, edit **output_handler.py**. `import GeoIP` ->`import geoip`

It seems no bugs right now...(still studying)
Hope you can fix the problem and sorry for my poor English.
