### ISSUE TITLE
How to setup HonSSH using two Raspberry Pi

### ISSUE THREAD

**Issue by javuchini** [tnich/honssh#59]
Dear Thomas,

In the Deployment Guide you indicate that 2 Raspberry Pi are being used. Could you explain it a little bit? I mean if you are using one Rasp for the HonSSH and the other one for the fake server, for the server. If it is so, could you give some clues about how to config them?

Another question is if could be set up using one only Rasperry. 

Many thanks in advance.

Best regards,
Javier

**Comment by Bifrozt** [comment]
Hi @javuchini ,

##### Setup

You have to Pi's
- pi1
- pi2 

pi1 should have two network interfaces
- if1
- if2
where if1 is the one that's exposed to the internet and if2 is connected to pi2.

Once you have this connected, follow the configuration guide from Thomas and you should be up and running in no time :)

##### Running on one machine
Setting up HonSSH using a single Pi (or any other type of machine) might work but, since you would be giving the attacker __complete__ access to that system, including all you collected data and HonSSH configuration it would defeat the purpose. If you want to run some type of honeypot using only a single node, take a look at [Kippo](https://github.com/desaster/kippo) from which HonSSH has evolved.

**Comment by tnich** [comment]
Couldn't have said it better myself!

Happy to answer any other questions that you may have during deployment. You should have my email now - unless I have met two Javiers in one day!

**Comment by javuchini** [comment]
Many thanks both of you. You're awesome!
